### ISSUE TITLE
Multiple Lines

### ISSUE THREAD

**Issue by bfernandesbfs** [brynbodayle/BABFrameObservingInputAccessoryView#1]
A feature that would be interesting is the support for multiple lines
When you press enter the textView increase up to the limit of NavigationViewController

**Comment by brynbodayle** [comment]
Hi @bfernandesbfs,

Thanks for the feature request. That feature would really be outside the scope of this control which is mainly focused on keeping an input view about the keyboard while supporting panning.

Here are a few alternative libraries which provide the feature you are looking for:
https://github.com/jessesquires/JSQMessagesViewController
https://github.com/HansPinckaers/GrowingTextView (A little outdated but has worked for me in the past)
